### ISSUE TITLE
While packaging for IOS

### ISSUE THREAD

**Issue by sumeet2k12** [myflashlab/Firebase-ANE#112]
How do set linker options

!STACK 0
java.lang.Exception: 
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_MyFlashLabsClass", referenced from:
      objc-class-ref in libcom.myflashlab.air.extensions.firebase.core.a(exFirebaseCore.o)
      objc-class-ref in libcom.myflashlab.air.extensions.facebook.a(ExtensionFB.o)
      objc-class-ref in libcom.myflashlab.air.extensions.facebook.a(ShareManager.o)
      objc-class-ref in libcom.myflashlab.air.extensions.facebook.a(FbAppDelegate.o)
      objc-class-ref in libcom.myflashlab.air.extensions.facebook.a(LogManager.o)
      objc-class-ref in libcom.myflashlab.air.extensions.webView.a(exWebview.o)
      objc-class-ref in libcom.myflashlab.air.extensions.firebase.fcm.a(exFirebaseFcm.o)
      ...
ld: symbol(s) not found for architecture arm64

	at com.adobe.flexide.multiplatform.ios.launching.IOSLaunchHandler.doPackage(IOSLaunchHandler.java:704)
	at com.adobe.flexide.multiplatform.ios.launching.IOSLaunchHandler.launch(IOSLaunchHandler.java:255)
	at com.adobe.flexide.launching.multiplatform.MultiPlatformLaunchDelegate.launch(MultiPlatformLaunchDelegate.java:184)
	at com.adobe.flexide.launching.AbstractFlexLaunchDelegate.launch(AbstractFlexLaunchDelegate.java:244)
	at com.adobe.flexide.launching.AbstractFlexLaunchDelegate.launch(AbstractFlexLaunchDelegate.java:134)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:854)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:703)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:928)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1132)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

**Comment by myflashlab** [comment]
check this out: https://github.com/myflashlab/Firebase-ANE/issues/110
