### ISSUE TITLE
Firebase NPE

### ISSUE THREAD

**Issue by DSigalov** [myflashlab/Firebase-ANE#126]
from google console
`
java.lang.NullPointerException: 
  at com.myflashlab.firebase.core.AirCommand.onConnectionFailed(AirCommand.java:407)
  at com.google.android.gms.common.internal.zzm.zzn(Unknown Source:0)
  at com.google.android.gms.internal.zzaat.zzc(Unknown Source:0)
  at com.google.android.gms.internal.zzaar.zzf(Unknown Source:0)
  at com.google.android.gms.internal.zzaar.onConnectionSuspended(Unknown Source:0)
  at com.google.android.gms.internal.zzaav.onConnectionSuspended(Unknown Source:0)
  at com.google.android.gms.internal.zzaag.onConnectionSuspended(Unknown Source:0)
  at com.google.android.gms.common.internal.zzl$1.onConnectionSuspended(Unknown Source:0)
  at com.google.android.gms.common.internal.zzf$zzd.handleMessage(Unknown Source:0)
  at android.os.Handler.dispatchMessage(Handler.java:111)
  at android.os.Looper.loop(Looper.java:194)
  at android.app.ActivityThread.main(ActivityThread.java:5549)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
`

**Comment by myflashlab** [comment]
these kind of error messages usually mean that you have missed a dependency. make sure you have them all. use this information as your reference: https://github.com/myflashlab/Firebase-ANE/blob/master/Dependencies.md

**Comment by myflashlab** [comment]
We have released V5 by the way. Make sure you are upgrading. If you still have a problem, please let me know so we can re-open the ticket
