### ISSUE TITLE
Core, Auth. App crashes at start. Auth no reaction

### ISSUE THREAD

**Issue by 4malik** [myflashlab/Firebase-ANE#130]
As you closed my issue https://github.com/myflashlab/common-dependencies-ANE/issues/12  in common dependencies with comments that i didn't add all the dependencies for firebase ANE. 
So the problem that after adding

```html
<!-- Required by the firebase_common.ane -->
<provider
	android:name="com.google.firebase.provider.FirebaseInitProvider"
	android:authorities="air.com.elimotoday.driver.firebaseinitprovider"
	android:exported="false"
	android:initOrder="100" />
```

my app began to crash at start.
Firebase.init() returns true. I can get config and trace params.

```javascript
var config:FirebaseConfig = Firebase.getConfig();
trace("default_web_client_id = " + 		config.default_web_client_id);
trace("firebase_database_url = " + 		config.firebase_database_url);
trace("gcm_defaultSenderId = " + 		config.gcm_defaultSenderId);
trace("google_api_key = " + 			config.google_api_key);
trace("google_app_id = " + 			config.google_app_id);
trace("google_crash_reporting_api_key = " + 	config.google_crash_reporting_api_key);
trace("google_storage_bucket = " + 		config.google_storage_bucket);
```

But Firebase Auth doesn't work. Auth.init() doesn't crash. I tried to call functions like Auth.createUserWithEmailAndPassword, Auth.signInWithEmail, Auth.verifyPhoneNumber, but no reaction, no any event to listener. I've added to firebase console auth type email, phone and google.
So may be it's really errors on manifest
So my manifest for android is
```html
<android>
    <containsVideo>true</containsVideo>
    <manifestAdditions>
      <![CDATA[
        <manifest android:installLocation="auto">
                
        <uses-sdk android:minSdkVersion="17" />
        <uses-sdk android:targetSdkVersion="23"/>
        
        <uses-feature android:required="true" android:name="android.hardware.touchscreen.multitouch" />
        
        <!-- LOCATION GROUP -->
        <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
        <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
        <uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
          
        <!-- PHONE GROUP -->
        <uses-permission android:name="android.permission.READ_PHONE_STATE" />  
          
        <!-- STORAGE GROUP --> 
        <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
        <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
          
        <!-- OTHERS -->
        <uses-permission android:name="android.permission.GET_TASKS" />
        <uses-permission android:name="android.permission.INTERNET" />
        <uses-permission android:name="android.permission.VIBRATE"/>
        <uses-permission android:name="android.permission.WAKE_LOCK" />
            
        <!-- Required for GCM && Required for firebase_iid -->
        <uses-permission android:name="android.permission.GET_ACCOUNTS" />
        <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
        <permission android:name="air.com.elimotoday.driver.permission.C2D_MESSAGE" android:protectionLevel="signature" />
        <uses-permission android:name="air.com.elimotoday.driver.permission.C2D_MESSAGE" />
          
        <!-- Required for GPS -->
        <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
        <uses-permission android:name="com.google.android.providers.gsf.permission.READ_GSERVICES" />
        <uses-permission android:name="com.google.android.gms.permission.ACTIVITY_RECOGNITION" />
          
        <application android:hardwareAccelerated="true" android:allowBackup="true">

          <activity android:hardwareAccelerated="true">
            <intent-filter>
              <action android:name="android.intent.action.MAIN" />
              <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter>
              <action android:name="android.intent.action.VIEW" />
              <category android:name="android.intent.category.BROWSABLE" />
              <category android:name="android.intent.category.DEFAULT" />
              <data android:scheme="air.com.elimotoday.driver" />
            </intent-filter>
          </activity>
          
          <!-- Required by the firebase_common.ane -->
          <provider
            android:name="com.google.firebase.provider.FirebaseInitProvider"
            android:authorities="air.com.elimotoday.driver.firebaseinitprovider"
            android:exported="false"
            android:initOrder="100" />
          
          <!-- Required by firebase_iid.ane -->
          <receiver android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver" android:exported="true" android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
              <action android:name="com.google.android.c2dm.intent.RECEIVE" />
              <category android:name="air.com.elimotoday.driver" />
            </intent-filter>
          </receiver>
          <receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
          <service android:name="com.google.firebase.iid.FirebaseInstanceIdService" android:exported="true">
            <intent-filter android:priority="-500">
              <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
          </service>
          
          <!-- Required by the googlePlayServices_basement.ane -->
          <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
          
          <!-- Required for GCM. Register the required listeners to receive gcm when app is closed -->
          <receiver android:name="com.elimotoday.driver.handler.GcmBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
              <action android:name="com.google.android.c2dm.intent.RECEIVE" />
              <category android:name="air.com.elimotoday.driver" />
            </intent-filter>
          </receiver>
          <service android:name="com.elimotoday.driver.handler.GcmMessageHandler" />
          <receiver android:name="com.elimotoday.driver.alarm.alarmTypes.Alarm_Notification" />
          
          <!-- Required for waking up the device when gcm notification arrives -->
          <activity android:name="com.elimotoday.driver.alarm.WakeActivity" android:theme="@style/Theme.Transparent" />
          
          <!-- required for html file select buttons -->
          <activity android:name="com.doitflash.webView.Pick" android:theme="@style/Theme.Transparent" />
          
        </application>
          
      </manifest>]]>
    </manifestAdditions>
  </android>

<extensions>
	<extensionID>com.myflashlab.air.extensions.firebase.auth</extensionID>
	<extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
	<extensionID>com.myflashlab.air.extensions.gcm</extensionID>
	<extensionID>com.myflashlab.air.extensions.permissionCheck</extensionID>
	<extensionID>com.myflashlab.air.extensions.udid</extensionID>
	<extensionID>com.myflashlab.air.extensions.webView</extensionID>
	
	<extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.firebase.auth</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.gcm</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.iid</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
</extensions>
```

java 1.8u111
air sdk 25
flash develop 5.2.0
flex 4.16

lib versions
androidSupport 24.2.2
overrideAir 4.0.0
firebase.core 5.0.0
firebase.common 11.0.2
firebase.iid 11.0.2
googlePlayServices.base 11.0.2
googlePlayServices.basement 11.0.2
googlePlayServices.iid 11.0.2

Please don't close the issue after your answer at once,

**Comment by 4malik** [comment]
Due to dependencies https://github.com/myflashlab/Firebase-ANE/blob/master/Dependencies.md I have to add googlePlayServices_tasks and googlePlayServices_appinvite. But when i added to extensions
```html
<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.appinvite</extensionID>
<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
```
i got an exception
```
dx tool failed:
UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzapy;
        at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
        at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
        at com.android.dx.command.dexer.Main.processClass(Main.java:737)
        at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)
        at com.android.dx.command.dexer.Main.access$300(Main.java:83)
        at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)
        at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
        at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
        at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
        at com.android.dx.command.dexer.Main.processOne(Main.java:637)
        at com.android.dx.command.dexer.Main.processAllFiles(Main.java:506)
        at com.android.dx.command.dexer.Main.runMultiDex(Main.java:335)
        at com.android.dx.command.dexer.Main.run(Main.java:245)
        at com.android.dx.command.dexer.Main.main(Main.java:215)
        at com.android.dx.command.Main.main(Main.java:106)

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/iid/zzc;
        at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
        at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
        at com.android.dx.command.dexer.Main.processClass(Main.java:737)
        at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)
        at com.android.dx.command.dexer.Main.access$300(Main.java:83)
        at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)
        at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
        at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
        at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
        at com.android.dx.command.dexer.Main.processOne(Main.java:637)
        at com.android.dx.command.dexer.Main.processAllFiles(Main.java:506)
        at com.android.dx.command.dexer.Main.runMultiDex(Main.java:335)
        at com.android.dx.command.dexer.Main.run(Main.java:245)
        at com.android.dx.command.dexer.Main.main(Main.java:215)
        at com.android.dx.command.Main.main(Main.java:106)
2 errors; aborting

APK setup creation FAILED.
```

**Comment by 4malik** [comment]
I tried to add android manifest from your example https://github.com/myflashlab/Firebase-ANE/blob/master/FD/application.xml

```html
<android>
  <manifestAdditions>
    <![CDATA[
      <manifest android:installLocation="auto">
              
        <uses-permission android:name="android.permission.INTERNET" />
        <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
        <uses-permission android:name="android.permission.WAKE_LOCK"/>
        
        <!-- Required by firebase_iid.ane -->
        <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
        <permission android:name="air.com.elimotoday.driver.permission.C2D_MESSAGE" android:protectionLevel="signature" />
        <uses-permission android:name="air.com.elimotoday.driver.permission.C2D_MESSAGE" />
        
        <application>
          <activity>
            <intent-filter>
              <action android:name="android.intent.action.MAIN" />
              <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter>
              <action android:name="android.intent.action.VIEW" />
              <category android:name="android.intent.category.BROWSABLE" />
              <category android:name="android.intent.category.DEFAULT" />
              <data android:scheme="air.com.elimotoday.driver" />
            </intent-filter>
          </activity>
            
          <!-- Required by the firebase_common.ane -->
          <provider
            android:name="com.google.firebase.provider.FirebaseInitProvider"
            android:authorities="air.com.elimotoday.driver.firebaseinitprovider"
            android:exported="false"
            android:initOrder="100" />
          
          <!-- Required by googlePlayServices_basement.ane -->
          <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
            
          <!-- Required by firebase_iid.ane -->
          <receiver
            android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
              <action android:name="com.google.android.c2dm.intent.RECEIVE" />
              <category android:name="air.com.elimotoday.driver" />
            </intent-filter>
          </receiver>
          <receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
          <service android:name="com.google.firebase.iid.FirebaseInstanceIdService" android:exported="true">
            <intent-filter android:priority="-500">
              <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
          </service>
            
          <!-- Required by googlePlayServices_base.ane -->
          <activity android:name="com.google.android.gms.common.api.GoogleApiActivity"
            android:theme="@android:style/Theme.Translucent.NoTitleBar"
            android:exported="false"/>
        
        </application>
      </manifest>
    ]]>
  </manifestAdditions>
</android>

<extensions>
  <extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
  
  <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
  <extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID>
  <extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
  <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.appinvite</extensionID>
  <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
  <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
  <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
  <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
</extensions>
```
but got the same error "dx tool failed: UNEXPECTED TOP-LEVEL EXCEPTION: java.lang.IllegalArgumentException: already added"

**Comment by myflashlab** [comment]
Ok, you have posted several versions of your manifest and I'm not sure which one is the latest, but here are some points you should consider:

1. Use FCM instead of GCM. GCM is deprecated and using it along with firebase can be trouble some and may cause conflicts.
2. Although you are using AIR 25, have you declared it in the [manifest top](https://github.com/myflashlab/Firebase-ANE/blob/master/AIR/Main-app.xml#L2)?
3. Are you compiling your app in shared mode? please don't, only use the captive mode.
4. Have you tested on different devices?

**Comment by 4malik** [comment]
Hi.
I removed all that are not about firebase so now i don't have gcm
2. yes ofc. im using <application xmlns="http://ns.adobe.com/air/application/25.0">
3. compiling in captive runtime
4. i have only one android device.

but listen with tasks and appinvite its crashin while packaging

**Comment by 4malik** [comment]
Its very interesting... i loaded all libraries and project started.
So final manifest
'''html
<application xmlns="http://ns.adobe.com/air/application/25.0">
...
<android>
    <manifestAdditions>
      <![CDATA[
        <manifest android:installLocation="auto">
                
          <uses-permission android:name="android.permission.INTERNET" />
          <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
          <uses-permission android:name="android.permission.WAKE_LOCK"/>
          
          
          <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
          <permission android:name="air.com.elimotoday.driver.permission.C2D_MESSAGE" android:protectionLevel="signature" />
          <uses-permission android:name="air.com.elimotoday.driver.permission.C2D_MESSAGE" />
          
          <application>
            <activity>
              <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
              </intent-filter>
              <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.BROWSABLE" />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:scheme="air.com.elimotoday.driver" />
              </intent-filter>
            </activity>
              
            
            <provider
              android:name="com.google.firebase.provider.FirebaseInitProvider"
              android:authorities="air.com.elimotoday.driver.firebaseinitprovider"
              android:exported="false"
              android:initOrder="100" />
            
            
            <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
              
            
            <receiver
              android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
              android:exported="true"
              android:permission="com.google.android.c2dm.permission.SEND" >
              <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <category android:name="air.com.elimotoday.driver" />
              </intent-filter>
            </receiver>
            <receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
            <service android:name="com.google.firebase.iid.FirebaseInstanceIdService" android:exported="true">
              <intent-filter android:priority="-500">
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
              </intent-filter>
            </service>
              
            
            <activity android:name="com.google.android.gms.common.api.GoogleApiActivity"
              android:theme="@android:style/Theme.Translucent.NoTitleBar"
              android:exported="false"/>
          
          </application>
        </manifest>
      ]]>
    </manifestAdditions>
  </android>

<extensions>
  <extensionID>com.myflashlab.air.extensions.inspector</extensionID>
	
  <extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
  <extensionID>com.myflashlab.air.extensions.permissionCheck</extensionID>
  <extensionID>com.myflashlab.air.extensions.udid</extensionID>
  <extensionID>com.myflashlab.air.extensions.webView</extensionID>
		
  <extensionID>com.janumedia.ane.deviceinfo</extensionID>
  <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
  <extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID>
  <extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
  <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.appinvite</extensionID>
  <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>		
  <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>		
  <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.iid</extensionID>		
  <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
  <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
</extensions>
'''

Now Im trying to run inspector and to try auth.

**Comment by myflashlab** [comment]
Happy to see it is finally working. It's very probable that the dependency ANEs were not all updated or something similar.
