### ISSUE TITLE
Android below 5 crash on startup. FirebaseInitProvider not found.

### ISSUE THREAD

**Issue by seilz2k5** [myflashlab/Firebase-ANE#143]
For Android devices below Android 5 (for example 4.2.2) i get this crash right on startup of the app:

FATAL EXCEPTION: main
                                                   java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/air.de.flashwater.game03-1.apk"],nativeLibraryDirectories=[/data/app-lib/air.de.flashwater.game03-1, /vendor/lib, /system/lib]]
                                                       at android.app.ActivityThread.installProvider(ActivityThread.java:5129)
                                                       at android.app.ActivityThread.installContentProviders(ActivityThread.java:4689)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4629)
                                                       at android.app.ActivityThread.access$1300(ActivityThread.java:167)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1438)
                                                       at android.os.Handler.dispatchMessage(Handler.java:107)
                                                       at android.os.Looper.loop(Looper.java:194)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5405)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:525)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:838)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/air.de.flashwater.game03-1.apk"],nativeLibraryDirectories=[/data/app-lib/air.de.flashwater.game03-1, /vendor/lib, /system/lib]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:53)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
                                                       at android.app.ActivityThread.installProvider(ActivityThread.java:5114)
                                                       at android.app.ActivityThread.installContentProviders(ActivityThread.java:4689) 
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4629) 
                                                       at android.app.ActivityThread.access$1300(ActivityThread.java:167) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1438) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                       at android.os.Looper.loop(Looper.java:194) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5405) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:525) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:838) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605) 
                                                       at dalvik.system.NativeStart.main(Native Method) 

Am i missing libraries?
I'm integrating:
AndroidSupport.ane v25.3.1
All firebase common dependencies v11.0.2
FirebaseCore.ane:
VERSION v5.0.0
FIREBASE_SDK_IOS v4.0.3
FIREBASE_SDK_ANDROID v11.0.2

All google play common dependencies v11.0.2
OverrideAir.ane v4.1.0

**Comment by seilz2k5** [comment]
I discovert that this is actually a multidexing issue on Android. I'm using Air25 and it seem that you have to add the android:name tag with multidexing if you exceed the reference limit of 64K on Android when implementing too many ane.
Solution is posted here:
https://forums.adobe.com/thread/2317654

**Comment by myflashlab** [comment]
Thanks for sharing this information. Hopefully others with similar problem can find this useful.
