### ISSUE TITLE
FCM ANE: Android app crashing when launch/open the app

### ISSUE THREAD

**Issue by mprabhu33** [myflashlab/Firebase-ANE#148]
## Environment ##
* Android API Version: 24
* Android OS Version: 7.0
* AIR SDK Version: 26.0
* ANE Maker: V 5.1.0 
* FCM: Latest
* Mobile: Moto G5 Plus
*MotoG5 plus Android OS version: 7.0
* MotoG5 plus Google play Services version: 11.3.02

## Problem Description ##
Android app crashing when launch/open the app with latest ANE Maker V 5.1.0 and FCM.
In the Moto g5 plus with OS version 7.0.
```xml
<android>
        <colorDepth>16bit</colorDepth>
        <manifestAdditions><![CDATA[
			<manifest android:installLocation="auto">
			    <uses-permission android:name="android.permission.INTERNET"/>
			    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
			    <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
			    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />	
			    <!-- Needed only if your app targets Android 5.0 (API level 21) or higher. -->
    			<uses-feature android:name="android.hardware.location.gps" android:required="false"/>
    			<uses-feature android:name="android.hardware.location.network" android:required="false" />
			    		   
			    <uses-permission android:name="android.permission.DISABLE_KEYGUARD"/>
			    <uses-permission android:name="android.permission.WAKE_LOCK"/>
			    
			    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
			    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
			    <uses-permission android:name="android.permission.BLUETOOTH"/>
			    
			    <uses-permission android:name="android.permission.CAMERA"/>
			    <uses-feature android:name="android.hardware.camera" android:required="false" />
                <uses-feature android:name="android.hardware.camera.front" android:required="false" />
				<uses-feature android:name="android.hardware.camera.autofocus" android:required="false" />
			   
				
				<!-- 
					Required by firebase_iid.ane 
					Change "air.com.symphonysummit.SummitServiceManagement51WS" to your own app package name
				-->
				<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
				<permission android:name="air.com.symphonysummit.SummitServiceManagement51WS.permission.C2D_MESSAGE" android:protectionLevel="signature" />
				<uses-permission android:name="air.com.symphonysummit.SummitServiceManagement51WS.permission.C2D_MESSAGE" />
				
				
			    
			    <application>
					 
					 <activity>
						<intent-filter>
							<action android:name="android.intent.action.MAIN" />
							<category android:name="android.intent.category.LAUNCHER" />
						</intent-filter>
						<intent-filter>
							<action android:name="android.intent.action.VIEW" />
							<category android:name="android.intent.category.BROWSABLE" />
							<category android:name="android.intent.category.DEFAULT" />
							<data android:scheme="air.com.symphonysummit.SummitServiceManagement51WS" />							
						</intent-filter>
					</activity>
					
					<!-- 
						Required by the firebase_common.ane 
						Change "air.com.symphonysummit.SummitServiceManagement51WS" to your own app package name
					-->
					<provider
			            android:name="com.google.firebase.provider.FirebaseInitProvider"
			            android:authorities="air.com.symphonysummit.SummitServiceManagement51WS.firebaseinitprovider"
			            android:exported="false"
			            android:initOrder="100" />
			
					<service
			            android:name="com.myflashlab.firebase.core.MyFirebaseInstanceIdService"
			            android:exported="true">
			            <intent-filter>
			                <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
			            </intent-filter>
			        </service>
					
					<!-- Required by googlePlayServices_basement.ane -->
					<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
					
					<!-- 
						Required by firebase_iid.ane 
						Change "air.com.symphonysummit.SummitServiceManagement51WS" to your own app package name
					-->
					<receiver
			            android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
			            android:exported="true"
			            android:permission="com.google.android.c2dm.permission.SEND" >
			            <intent-filter>
			                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
			                <category android:name="air.com.symphonysummit.SummitServiceManagement51WS" />
			            </intent-filter>
			        </receiver>
					<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
					<service android:name="com.google.firebase.iid.FirebaseInstanceIdService" android:exported="true">
			            <intent-filter android:priority="-500">
			                <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
			            </intent-filter>
			        </service>
					
					<!-- Required by googlePlayServices_base.ane -->
					<activity android:name="com.google.android.gms.common.api.GoogleApiActivity"
			                  android:theme="@android:style/Theme.Translucent.NoTitleBar"
			                  android:exported="false"/>
							  
					
					<!-- Required by firebase_messaging.ane -->
					<service android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingService">
						<intent-filter>
							<action android:name="com.google.firebase.MESSAGING_EVENT"/>
						</intent-filter>
					</service>
					<service android:name="com.myflashlab.firebase.fcm.MyFirebaseInstanceIDService">
						<intent-filter>
							<action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
						</intent-filter>
					</service>
					<activity 
						android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingIntent" 
						android:theme="@style/Theme.Transparent"
						android:exported="false"
						android:noHistory="true"
						android:clearTaskOnLaunch="true"
						android:hardwareAccelerated="false"
						android:stateNotNeeded="true">
						<intent-filter>
							<action android:name="MY_INTENT" />
							<category android:name="android.intent.category.DEFAULT" />
						</intent-filter>
					</activity>
							
        		</application>
			</manifest>
			   
			
		]]></manifestAdditions>
    </android>

   <extensions>
    	<extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
        <extensionID>com.myflashlab.air.extensions.firebase.fcm</extensionID>
        <extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
    	<extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.appinvite</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.messaging</extensionID>
    </extensions>
```
* Copy your Actionscript code.
```actionscript
private function initFCMCore():void
		{
			
			var isConfigFound:Boolean = Firebase.init();
			writeLog("Firebase Init.. " + isConfigFound);
			
			if (isConfigFound)
			{
				var config:FirebaseConfig = Firebase.getConfig();
				writeLog("default_web_client_id = " + 			config.default_web_client_id);
				writeLog("firebase_database_url = " + 			config.firebase_database_url);
				writeLog("gcm_defaultSenderId = " + 			config.gcm_defaultSenderId);
				writeLog("google_api_key = " + 				config.google_api_key);
				writeLog("google_app_id = " + 					config.google_app_id);
				writeLog("google_crash_reporting_api_key = " + config.google_crash_reporting_api_key);
				writeLog("google_storage_bucket = " + 			config.google_storage_bucket);
				
				// You must initialize any of the other Firebase children after a successfull initialization
				// of the Core ANE.
				writeLog("Firebase.os = " + 			Firebase.os);
				writeLog("Firebase.ANDROID = " + 			Firebase.ANDROID);
				if (Firebase.os == Firebase.ANDROID)
				{
					writeLog("checkGoogleAvailability... ");
					Firebase.checkGoogleAvailability(onCheckResult);
				}
				else 
				{
					onCheckResult(Firebase.SUCCESS);
				}
			}
			else
			{
				writeLog("Config file is not found!");
			}
		}
		
		private function onCheckResult($result:int):void
		{
			writeLog("onCheckResult... "+$result);
			switch($result)
			{
				case Firebase.SUCCESS:					
					writeLog("checkGoogleAvailability result = SUCCESS");
					initFCM();					
					break;
				case Firebase.SERVICE_MISSING:
					
					writeLog("checkGoogleAvailability result = SERVICE_MISSING");
					
					break;
				case Firebase.SERVICE_VERSION_UPDATE_REQUIRED:
					
					writeLog("checkGoogleAvailability result = SERVICE_VERSION_UPDATE_REQUIRED");
					
					break;
				case Firebase.SERVICE_UPDATING:
					
					writeLog("checkGoogleAvailability result = SERVICE_UPDATING");
					
					break;
				case Firebase.SERVICE_DISABLED:
					
					writeLog("checkGoogleAvailability result = SERVICE_DISABLED");
					
					break;
				case Firebase.SERVICE_INVALID:
					
					writeLog("checkGoogleAvailability result = SERVICE_INVALID");
					
					break;
			}
		}
		
		private function initFCM():void
		{
			writeLog("FCM Init.. " );
			FCM.init();
			FCM.listener.addEventListener(FcmEvents.TOKEN_REFRESH, onTokenRefresh);
			FCM.listener.addEventListener(FcmEvents.MESSAGE, onMessage);
			
			var tokenID:String = FCM.getToken();
			writeLog("TokenID:" + tokenID);
			if(tokenID == null || String(tokenID) == "null" || tokenID == "")
			{
				startTokenTimer();
			}else
			{
				saveTokenID(tokenID);
			}
			
		}
```
## Steps to Reproduce ##
Package the app with latest ANE Maker V5.1.0 and latest Dependencies
androidSupport.ane V25.3.1
overrideAir.ane V4.1.0
firebase_common.ane V11.0.2
firebase_iid.ane V11.0.2
googlePlayServices_base.ane V11.0.2
googlePlayServices_basement.ane V11.0.2
googlePlayServices_tasks.ane V11.0.2
googlePlayServices_appinvite.ane V11.0.2
firebaseCore.ane V5.1.0
firebase_messaging.ane V11.0.2	

Android crashing when launch/open app in the Moto G5 plus mobile
MotoG5 plus Android OS version: 7.0
MotoG5 plus Google play Services: 11.3.02

Could you please test with latest ANE Maker V5.1.0 with Google play service 11.3.02?
Anything missed in the manifest.xml or ANE?

Please let me know.

**Comment by myflashlab** [comment]
could you also send us the error logcat stack?

**Comment by mprabhu33** [comment]
How to get error logcat? Am testing directly on android device not simulator.
IDE: FlashBuilder 4.6

**Comment by myflashlab** [comment]
simply run AndroidStudio and open the logcat window. it will show all the logs from your Android device and when an error occurs it will out put it. read here: https://www.google.com/search?q=how+to+open+logcat+android+studio

**Comment by mprabhu33** [comment]
08-29 15:13:36.716 25705-25720/? E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
                                                   Process: air.com.symphonysummit.SummitServiceManagement51WS, PID: 25705
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'void com.adobe.fre.FREContext.dispatchStatusEventAsync(java.lang.String, java.lang.String)' on a null object reference
                                                       at com.myflashlab.firebase.core.MyFirebaseInstanceIdService.onTokenRefresh(MyFirebaseInstanceIdService.java:19)
                                                       at com.google.firebase.iid.FirebaseInstanceIdService.zza(Unknown Source)
                                                       at com.google.firebase.iid.FirebaseInstanceIdService.handleIntent(Unknown Source)
                                                       at com.google.firebase.iid.zzc.run(Unknown Source)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                       at java.lang.Thread.run(Thread.java:761)

**Comment by myflashlab** [comment]
please contact us through http://www.myflashlabs.com/contact/ with your myflashlab's account username so we can send you a newer version of the firebasecore so you can test again and see if the error occurs again. Thanks for your cooperation.

**Comment by mprabhu33** [comment]
Thanks for quick fix in FirebaseCore.
Generated new firebaseCore.ane with newer version of Test-V5.1.0.air
Android app is working fine now. No crashing when application launch/open.
Am closing this issue now.

Please update the same in the next version of ANEMaker.

**Comment by myflashlab** [comment]
V5.1.1 is now released.
