### ISSUE TITLE
Crash on receiving FCM message (Android)

### ISSUE THREAD

**Issue by JokerDen** [myflashlab/Firebase-ANE#158]
App is crashing (while in background) when I'm trying to send notification via Firebase Console.

```
java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
    at com.freshplanet.ane.AirPushNotification.CreateNotificationTask.onPostExecute(CreateNotificationTask.java:160)
    at com.freshplanet.ane.AirPushNotification.CreateNotificationTask.onPostExecute(CreateNotificationTask.java:50)
    at android.os.AsyncTask.finish(AsyncTask.java:632)
    at android.os.AsyncTask.access$600(AsyncTask.java:177)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
    at android.os.Handler.dispatchMessage(Handler.java:111)
    at android.os.Looper.loop(Looper.java:194)
    at android.app.ActivityThread.main(ActivityThread.java:5556)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
```

**Comment by myflashlab** [comment]
As the error log shows, this is happening in other ANEs rather than Firebase children.

**Comment by JokerDen** [comment]
Oops, sorry. Just confused with two ANEs for push notifications.
