### ISSUE TITLE
Android 4.2.2 application immediately crashes

### ISSUE THREAD

**Issue by CrazyFlasher** [myflashlab/Firebase-ANE#169]
Applications immediately crashes on Android 4.2.2
Log:
```
12-14 14:11:39.583	17063	17063	W	dalvikvm	threadid=1: thread exiting with uncaught exception (group=0x4122c9a8)
12-14 14:11:39.583	17063	17063	W	dalvikvm	threadid=1: uncaught exception occurred
12-14 14:11:39.583	17063	17063	W	System.err	java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/ee.Javelin.SpotlightRoomEscape-1.apk"],nativeLibraryDirectories=[/data/app-lib/ee.Javelin.SpotlightRoomEscape-1, /vendor/lib, /system/lib]]
12-14 14:11:39.587	17063	17063	W	System.err		at android.app.ActivityThread.installProvider(ActivityThread.java:5121)
12-14 14:11:39.587	17063	17063	W	System.err		at android.app.ActivityThread.installContentProviders(ActivityThread.java:4681)
12-14 14:11:39.588	17063	17063	W	System.err		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4621)
12-14 14:11:39.588	17063	17063	W	System.err		at android.app.ActivityThread.access$1300(ActivityThread.java:165)
12-14 14:11:39.588	17063	17063	W	System.err		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1433)
12-14 14:11:39.588	17063	17063	W	System.err		at android.os.Handler.dispatchMessage(Handler.java:107)
12-14 14:11:39.589	17063	17063	W	System.err		at android.os.Looper.loop(Looper.java:194)
12-14 14:11:39.589	17063	17063	W	System.err		at android.app.ActivityThread.main(ActivityThread.java:5391)
12-14 14:11:39.589	17063	17063	W	System.err		at java.lang.reflect.Method.invokeNative(Native Method)
12-14 14:11:39.589	17063	17063	W	System.err		at java.lang.reflect.Method.invoke(Method.java:525)
12-14 14:11:39.589	17063	17063	W	System.err		at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
12-14 14:11:39.590	17063	17063	W	System.err		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
12-14 14:11:39.590	17063	17063	W	System.err		at dalvik.system.NativeStart.main(Native Method)
```

**Comment by CrazyFlasher** [comment]
Addind this to manifest resolved the problem:
```
android:name="android.support.multidex.MultiDexApplication
```

**Comment by tconkling** [comment]
For anyone else confused about where to put this line: it belongs in `<application>`, like so: `<application android:name="android.support.multidex.MultiDexApplication">`

@myflashlab: please update your docs to make this clear!
