### ISSUE TITLE
FCM error

### ISSUE THREAD

**Issue by WoojinLIM** [myflashlab/Firebase-ANE#183]
Before opening a new issue, make sure you are using the latest available ANE. If the ANE is dependent on other libraries or dependencies, also make sure they are the latest versions.

## Environment ##
* Android API Version: 23
* AIR SDK Version: 28

## Problem Description ##
My source is..
https://github.com/WoojinLIM/FullinkeyService

## Steps to Reproduce ##
I was successful in getting the FCM token.
However, when you send a message from Firebase, the following error message is displayed on the device and the application is terminated.
Error message is "Unfortunately, FullinkeyService-debug has stopped."

How do I fix it?

## Logcat ##
```
02-18 12:18:27.729 2785-2912/? I/StatusController: Last foreground:com.miui.home uid:10022 Current foreground:air.FullinkeyService.debug uid:10153
02-18 12:18:27.730 2785-2912/? I/WtProcessController: FOREGROUND INFO: name=air.FullinkeyService.debug uid=10153 pid=20095 TaskId:58
02-18 12:18:27.992 20095-20095/? D/AccessibilityManager: current package=air.FullinkeyService.debug, accessibility manager mIsFinalEnabled=false, mOptimizeEnabled=true, mIsUiAutomationEnabled=false, mIsInterestedPackage=false
02-18 12:18:29.470 1488-1575/? I/ActivityManager: Displayed air.FullinkeyService.debug/.AppEntry: +1s787ms (total +7s198ms)
02-18 12:18:29.470 1488-1575/? I/Timeline: Timeline: Activity_windows_visible id: ActivityRecord{21c4a8c u0 air.FullinkeyService.debug/.AppEntry t58} time:9214296
02-18 12:18:29.470 20095-20095/? I/air.FullinkeyService.debug: FirebaseCore(AirCommand) command:initFirebase
02-18 12:18:29.471 20095-20095/? I/air.FullinkeyService.debug: FirebaseCore(AirCommand) initFirebase > passed the initial initialization
02-18 12:18:29.472 20095-20095/? I/air.FullinkeyService.debug: FirebaseCore(AirCommand) initFirebase > initialization completed
02-18 12:18:29.473 20095-20095/? I/air.FullinkeyService.debug: checkGoogleAvailability result = SUCCESS
02-18 12:18:29.481 20095-20095/? I/air.FullinkeyService.debug: ftzCb7xfv9I:APA91bEMX7OpPY05qEhWjevmdBU6Yj1xWMvjG7DTAISgY8V1YLIWAZ_oKfsBA6-WCmweeHLKha5_lLMoRUChngbqe6Hb_s_vhBia7Dm69twaNSWVyNGvZv3KYJ_zIZfvQsdRDKDW32I5
02-18 12:18:29.481 20095-20095/? I/air.FullinkeyService.debug: FirebaseFCM(AirCommand) token is: ftzCb7xfv9I:APA91bEMX7OpPY05qEhWjevmdBU6Yj1xWMvjG7DTAISgY8V1YLIWAZ_oKfsBA6-WCmweeHLKha5_lLMoRUChngbqe6Hb_s_vhBia7Dm69twaNSWVyNGvZv3KYJ_zIZfvQsdRDKDW32I5
02-18 12:18:29.481 20095-20095/? I/air.FullinkeyService.debug: FirebaseFCM(AirCommand) id: ftzCb7xfv9I
02-18 12:18:29.482 20095-20095/? I/air.FullinkeyService.debug: FirebaseFCM(AirCommand) token is: ftzCb7xfv9I:APA91bEMX7OpPY05qEhWjevmdBU6Yj1xWMvjG7DTAISgY8V1YLIWAZ_oKfsBA6-WCmweeHLKha5_lLMoRUChngbqe6Hb_s_vhBia7Dm69twaNSWVyNGvZv3KYJ_zIZfvQsdRDKDW32I5
02-18 12:18:29.482 20095-20095/? I/air.FullinkeyService.debug: FirebaseFCM(AirCommand) id: ftzCb7xfv9I
02-18 12:18:29.659 1488-1575/? I/WindowManager: Destroying surface Surface(name=Starting air.FullinkeyService.debug) called by com.android.server.wm.WindowStateAnimator.destroySurface:2043 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:895 com.android.server.wm.WindowState.destroyOrSaveSurface:2116 com.android.server.wm.AppWindowToken.destroySurfaces:363 com.android.server.wm.WindowStateAnimator.finishExit:565 com.android.server.wm.WindowStateAnimator.stepAnimationLocked:491 com.android.server.wm.WindowAnimator.updateWindowsLocked:313 com.android.server.wm.WindowAnimator.animateLocked:714 
02-18 12:18:29.934 20095-20095/? I/air.FullinkeyService.debug: onTokenRefresh = ftzCb7xfv9I:APA91bEMX7OpPY05qEhWjevmdBU6Yj1xWMvjG7DTAISgY8V1YLIWAZ_oKfsBA6-WCmweeHLKha5_lLMoRUChngbqe6Hb_s_vhBia7Dm69twaNSWVyNGvZv3KYJ_zIZfvQsdRDKDW32I5
02-18 12:19:22.516 20095-20095/? I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.messaging.FirebaseMessagingService" on path: DexPathList[[zip file "/data/app/air.FullinkeyService.debug-2/base.apk"],nativeLibraryDirectories=[/data/app/air.FullinkeyService.debug-2/lib/arm, /system/fake-libs, /data/app/air.FullinkeyService.debug-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
02-18 12:19:22.519 20095-20095/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: air.FullinkeyService.debug, PID: 20095
                                                   java.lang.RuntimeException: Unable to instantiate service com.myflashlab.firebase.fcm.MyFirebaseMessagingService: java.lang.ClassNotFoundException: Didn't find class "com.myflashlab.firebase.fcm.MyFirebaseMessagingService" on path: DexPathList[[zip file "/data/app/air.FullinkeyService.debug-2/base.apk"],nativeLibraryDirectories=[/data/app/air.FullinkeyService.debug-2/lib/arm, /system/fake-libs, /data/app/air.FullinkeyService.debug-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
                                                       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3197)
                                                       at android.app.ActivityThread.-wrap5(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1596)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:163)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6237)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.myflashlab.firebase.fcm.MyFirebaseMessagingService" on path: DexPathList[[zip file "/data/app/air.FullinkeyService.debug-2/base.apk"],nativeLibraryDirectories=[/data/app/air.FullinkeyService.debug-2/lib/arm, /system/fake-libs, /data/app/air.FullinkeyService.debug-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3194)
                                                       at android.app.ActivityThread.-wrap5(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1596) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:163) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6237) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
                                                   	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/messaging/FirebaseMessagingService;
                                                       at java.lang.VMClassLoader.findLoadedClass(Native Method)
                                                       at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
                                                       		... 10 more
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.messaging.FirebaseMessagingService" on path: DexPathList[[zip file "/data/app/air.FullinkeyService.debug-2/base.apk"],nativeLibraryDirectories=[/data/app/air.FullinkeyService.debug-2/lib/arm, /system/fake-libs, /data/app/air.FullinkeyService.debug-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                       		... 13 more
02-18 12:19:22.528 2785-2912/? I/WtProcessController: Receive am_crash event for pid: 20095 pkg = air.FullinkeyService.debug
02-18 12:19:22.528 2785-2912/? W/KloServer: Aborted broadcast does not supprt for: air.FullinkeyService.debug
02-18 12:19:22.528 1488-2836/? W/ActivityManager:   Force finishing activity air.FullinkeyService.debug/.AppEntry
02-18 12:19:22.585 1488-1763/? I/WindowManager: WIN DEATH: Window{29e50fd u0 air.FullinkeyService.debug/air.FullinkeyService.debug.AppEntry}
02-18 12:19:22.585 1488-1763/? W/WindowManager: Force-removing child win Window{c2f6c8f u0 SurfaceView - air.FullinkeyService.debug/air.FullinkeyService.debug.AppEntry} from container Window{29e50fd u0 air.FullinkeyService.debug/air.FullinkeyService.debug.AppEntry}
02-18 12:19:22.585 1488-2822/? I/ActivityManager: Process air.FullinkeyService.debug (pid 20095) has died
```

**Comment by myflashlab** [comment]
well, the error message on the first line says ```java.lang.RuntimeException: Unable to instantiate service com.myflashlab.firebase.fcm.MyFirebaseMessagingService: java.lang.ClassNotFoundException: Didn't find class "com.myflashlab.firebase.fcm.MyFirebaseMessagingService" on path``` which means

**Comment by WoojinLIM** [comment]
[https://github.com/WoojinLIM/FullinkeyService/blob/master/capture1.JPG](url)
[https://github.com/WoojinLIM/FullinkeyService/blob/master/capture2.JPG](url)

Capture and link my project settings.

**Comment by myflashlab** [comment]
based on your screenshots, I can clearly see that you are missing the [firebase_messaging.ane](https://github.com/myflashlab/common-dependencies-ANE/blob/master/firebase/firebase_messaging.ane). please read this wiki with more attention: https://github.com/myflashlab/Firebase-ANE/wiki/G.1-Add-FCM and make sure you have set everything correctly.

If you are a club member, you can just use the [ANELAB Software](https://github.com/myflashlab/ANE-LAB/) and it will do all these confusing setup for you automatically.
