### ISSUE TITLE
 Application quits receiving message fcm

### ISSUE THREAD

**Issue by heliomarch** [myflashlab/Firebase-ANE#252]
## Environment ##
* 30.0.0107

## 
I can already get the token but when the message arrives the application closes and gives an error.
I gathered the information in Android Studio and it goes below ##
```xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<!-- 
	Usage:

	To localize the description, use the following format for the description element.
	<description>
	<text xml:lang="en">English App description goes here</text>
	<text xml:lang="fr">French App description goes here</text>
	<text xml:lang="ja">Japanese App description goes here</text>
	</description>

	To localize the name, use the following format for the name element.
	<name>
	<text xml:lang="en">English App name goes here</text>
	<text xml:lang="fr">French App name goes here</text>
	<text xml:lang="ja">Japanese App name goes here</text>
	</name>
-->
<application xmlns="http://ns.adobe.com/air/application/30.0">
  <id>acionamentoosadmin</id>
  <versionNumber>1.0.0</versionNumber>
  <versionLabel>1.0.0</versionLabel>
  <filename>acionamento_osadmin</filename>
  <description/>
  <name>acionamento_osadmin</name>
  <copyright/>
  <initialWindow>
    <content>acionamento_osadmin.swf</content>
    <systemChrome>standard</systemChrome>
    <transparent>false</transparent>
    <visible>true</visible>
    <fullScreen>true</fullScreen>
    <aspectRatio>portrait</aspectRatio>
    <renderMode>cpu</renderMode>
    <autoOrients>false</autoOrients></initialWindow>
  <icon/>
  <customUpdateUI>false</customUpdateUI>
  <allowBrowserInvocation>false</allowBrowserInvocation>
  
  <supportedLanguages>pt</supportedLanguages>
  <android>
    <manifestAdditions><![CDATA[<manifest>
	<uses-sdk android:targetSdkVersion="26" />
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
<uses-permission android:name="android.permission.min.permission.C2D_MESSAGE"/>
<uses-permission android:name="android.permission.c2dm.permission.RECEIVE"/>
<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
<permission android:name="air.acionamentoosadmin.permission.C2D_MESSAGE" android:protectionLevel="signature" />
<uses-permission android:name="air.acionamentoosadmin.permission.C2D_MESSAGE" />
<uses-permission android:name="android.permission.WAKE_LOCK" />




<application android:hardwareAccelerated="true" android:allowBackup="true" android:name="android.support.multidex.MultiDexApplication">

			<activity>
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
			<intent-filter>
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.BROWSABLE" />
				<category android:name="android.intent.category.DEFAULT" />
				
				<!-- Change "[YOUR_APP_PACKAGE_NAME]" to your own app package name -->
				<data android:scheme="air.acionamentoosadmin" />
			</intent-filter>
			</activity>

		<provider
			android:name="com.google.firebase.provider.FirebaseInitProvider"
			android:authorities="air.acionamentoosadmin.firebaseinitprovider"
			android:exported="false"
			android:initOrder="100"/>
			
		<service android:name="com.google.firebase.components.ComponentDiscoveryService">

            <!-- Required by firebase_iid.ane -->
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.iid.Registrar"
                android:value="com.google.firebase.components.ComponentRegistrar"/>

            <!-- Required by firebase_measurementConnectorImpl.ane -->
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar"/>

        </service>
		<meta-data 
			android:name="com.google.android.gms.version" 
			android:value="@integer/google_play_services_version" />
			
			
			
			<receiver
            android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <category android:name="air.acionamentoosadmin" />
            </intent-filter>
        </receiver>
		<service android:name="com.google.firebase.iid.FirebaseInstanceIdService" android:exported="true">
            <intent-filter android:priority="-500">
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
        </service>
		
		<!-- Required by googlePlayServices_base.ane -->
		<activity android:name="com.google.android.gms.common.api.GoogleApiActivity"
                  android:theme="@android:style/Theme.Translucent.NoTitleBar"
                  android:exported="false"/>
				
					
		<service android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingService">
					<intent-filter>
						<action android:name="com.google.firebase.MESSAGING_EVENT"/>
					</intent-filter>
				</service>
				<activity 
					android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingIntent" 
					android:theme="@style/Theme.Transparent"
					android:exported="false"
					android:noHistory="true"
					android:clearTaskOnLaunch="true"
					android:hardwareAccelerated="false"
					android:stateNotNeeded="true">
					<intent-filter>
						<action android:name="MY_INTENT" />
						<category android:name="android.intent.category.DEFAULT" />
					</intent-filter>
				</activity>

</application>

</manifest>]]></manifestAdditions>
  </android>  
  <extensions>
    <extensionID>com.doitflash.air.extensions.inputDialog</extensionID>
    <extensionID>com.doitflash.air.extensions.toast</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.stats</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.messaging</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.fcm</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.appinvite</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.arch</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.core</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.v4</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.analytics</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.analytics.impl</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.ads</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.measurementBase</extensionID>
  </extensions>
</application>

```
```actionscript
import com.doitflash.consts.Direction;
	import com.doitflash.consts.Orientation;
	import com.doitflash.mobileProject.commonCpuSrc.DeviceInfo;
	import com.doitflash.starling.utils.list.List;
	import com.doitflash.text.modules.MySprite;
	
	import com.luaye.console.C;
	
	import flash.desktop.NativeApplication;
	import flash.desktop.SystemIdleMode;
	import flash.display.Sprite;
	import flash.display.StageAlign;
	import flash.display.StageScaleMode;
	import flash.events.Event;
	import flash.events.InvokeEvent;
	import flash.events.KeyboardEvent;
	import flash.events.MouseEvent;
	import flash.text.AntiAliasType;
	import flash.text.TextField;
	import flash.text.TextFieldAutoSize;
	import flash.text.TextFormat;
	import flash.text.TextFormatAlign;
	import flash.ui.Keyboard;
	import flash.ui.Multitouch;
	import flash.ui.MultitouchInputMode;
	
	import com.myflashlab.air.extensions.firebase.core.*;
	import com.myflashlab.air.extensions.firebase.fcm.*;
	import com.myflashlab.air.extensions.dependency.OverrideAir;
	
	var tokenrar:String;
	
			Multitouch.inputMode = MultitouchInputMode.GESTURE;
			NativeApplication.nativeApplication.addEventListener(Event.ACTIVATE, handleActivate);
			NativeApplication.nativeApplication.addEventListener(Event.DEACTIVATE, handleDeactivate);
			NativeApplication.nativeApplication.addEventListener(InvokeEvent.INVOKE, onInvoke);
			NativeApplication.nativeApplication.addEventListener(KeyboardEvent.KEY_DOWN, handleKeys);
			
			stage.addEventListener(Event.RESIZE, onResize);
			//stage.scaleMode = StageScaleMode.NO_SCALE;
			stage.align = StageAlign.TOP_LEFT;
			
			C.startOnStage(this, "`");
			C.commandLine = false;
			C.commandLineAllowed = false;
			C.x = 20;
			C.width = 250;
			C.height = 150;
			C.strongRef = true;
			C.visible = true;
			C.scaleX = C.scaleY = DeviceInfo.dpiScaleMultiplier;		
			
			
			
			function onInvoke(e:InvokeEvent):void
		{
			var payload:Object = FCM.parsePayloadFromArguments(e.arguments);
			
			if (payload) // If available, it means that the Invoke listener contains FCM data
			{
				C.log("---------------------------------");
				for (var name:String in payload)
				{
					C.log(name + " = " + payload[name]);
				}
				C.log("---------------------------------");
			}
		}
			
			
		function handleActivate(e:Event):void
		{
			NativeApplication.nativeApplication.systemIdleMode = SystemIdleMode.KEEP_AWAKE;
		}
		
		 function handleDeactivate(e:Event):void
		{
			NativeApplication.nativeApplication.systemIdleMode = SystemIdleMode.NORMAL;
		}
		
		
		function handleKeys(e:KeyboardEvent):void
		{
			if(e.keyCode == Keyboard.BACK)
            {
				e.preventDefault();
				NativeApplication.nativeApplication.exit();
            }
		}
		
		
		function onResize(e:*=null):void
		{
			
		}	
		
		init();
			
		
		function init():void
		{
			// remove this line in production build or pass null as the delegate
			//OverrideAir.enableDebugger(myDebuggerDelegate);
			
			var isConfigFound:Boolean = Firebase.init();
			
			if (isConfigFound)
			{
				var config:FirebaseConfig = Firebase.getConfig();
				C.log("default_web_client_id = " + 			config.default_web_client_id);
				C.log("firebase_database_url = " + 			config.firebase_database_url);
				C.log("gcm_defaultSenderId = " + 			config.gcm_defaultSenderId);
				C.log("google_api_key = " + 				config.google_api_key);
				C.log("google_app_id = " + 					config.google_app_id);
				C.log("google_crash_reporting_api_key = " + config.google_crash_reporting_api_key);
				C.log("google_storage_bucket = " + 			config.google_storage_bucket);
				C.log("project_id = " + 					config.project_id);
				
				// FCM needs Google Services so, before using FCM, we need to check that first.
				// https://firebase.google.com/docs/cloud-messaging/android/client#sample-play
				if (Firebase.os == Firebase.ANDROID) Firebase.checkGoogleAvailability(onCheckResult);
				else onCheckResult(Firebase.SUCCESS);
			}
			else
			{
				C.log("Config file is not found!");
			}
		}
		
		function onCheckResult($result:int):void
		{
			switch($result)
			{
				case Firebase.SUCCESS:
					
					C.log("checkGoogleAvailability result = SUCCESS");
					
					// now you can use FCM
					initFCM();
					//onResize();
					
				break;
				case Firebase.SERVICE_MISSING:
					
					C.log("checkGoogleAvailability result = SERVICE_MISSING");
					
				break;
				case Firebase.SERVICE_VERSION_UPDATE_REQUIRED:
					
					C.log("checkGoogleAvailability result = SERVICE_VERSION_UPDATE_REQUIRED");
					
				break;
				case Firebase.SERVICE_UPDATING:
					
					C.log("checkGoogleAvailability result = SERVICE_UPDATING");
					
				break;
				case Firebase.SERVICE_DISABLED:
					
					C.log("checkGoogleAvailability result = SERVICE_DISABLED");
					
				break;
				case Firebase.SERVICE_INVALID:
					
					C.log("checkGoogleAvailability result = SERVICE_INVALID");
				
				break;
			}
		}
		
		
		function initFCM():void
		{
			FCM.init(); 
			FCM.listener.addEventListener(FcmEvents.TOKEN_REFRESH, onTokenRefresh);
			FCM.listener.addEventListener(FcmEvents.MESSAGE, onMessage);
			
		}
		
		btn1.addEventListener(MouseEvent.CLICK, getToken);
			function getToken(e:MouseEvent):void
			{
			pegatoken();	
			}
			
			function pegatoken():void
			{
				
				FCM.getInstanceId(onTokenReceived);
			}
			
			
			function onTokenReceived(token:String, error:String):void
			{
				
				if(error)
				{
					trace("onTokenReceived error: " + error);
					C.log("onTokenReceived error: " + error);
				}
				
				if(token)
				{
					tokenrar=token;
					trace("token: " + token);
					C.log("token: " + token);
				}
				}
				
		function onTokenRefresh(e:FcmEvents):void
		{
			trace("onTokenRefresh = " + e.token);
			C.log("onTokenRefresh = " + e.token);
		}
		
		
		function onMessage(e:FcmEvents):void
		{
			trace(e.msg);
			var payload:Object = FCM.parsePayloadFromString(e.msg);
			
			if (payload)
			{
				for (var name:String in payload)
				{
					C.log(name + " = " + payload[name]);
				}
			}
		}
```

## ao acionar o aplicativo ##

##10-02 15:00:40.708 485-657/? E/AndroidRuntime: FATAL EXCEPTION: Firebase-MyFirebaseMessagingService
    Process: air.acionamentoosadmin, PID: 485
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
        at com.google.firebase.messaging.zzb.zzc(Unknown Source)
        at com.google.firebase.messaging.zzb.zze(Unknown Source)
        at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source)
        at com.google.firebase.iid.zzc.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/data/app/air.acionamentoosadmin-1/base.apk"],nativeLibraryDirectories=[/data/app/air.acionamentoosadmin-1/lib/arm, /data/app/air.acionamentoosadmin-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.google.firebase.messaging.zzb.zzc(Unknown Source) 
        at com.google.firebase.messaging.zzb.zze(Unknown Source) 
        at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source) 
        at com.google.firebase.iid.zzc.run(Unknown Source) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source) 
        at java.lang.Thread.run(Thread.java:818) 
    	Suppressed: java.lang.ClassNotFoundException: com.google.firebase.analytics.connector.AnalyticsConnector
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 9 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
 ##

**Comment by myflashlab** [comment]
Whenever you see an error like “classNotFound” you can be sure that you are missing a dependency!

Let me name one: firebase_measurementConnectorImpl.ane V16.0.1

Please check this page and make sure you are implementing all the dependences: https://github.com/myflashlab/Firebase-ANE/blob/master/Dependencies.md

**Comment by heliomarch** [comment]
Hadi you are the best. Wwwwooooooooooooooooooooooooouuuuuu is amazing. God. Tank s.
