### ISSUE TITLE
FATAL EXCEPTION: TokenRefresher

### ISSUE THREAD

**Issue by AlexUrrutia** [myflashlab/Firebase-ANE#263]
**The app crashes when the user token expires after 60 minutes:**

```
11-19 19:08:25.307 20971-20990/? E/AndroidRuntime: FATAL EXCEPTION: TokenRefresher
    Process: air.com.myapp, PID: 20971
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/flags/Flag;
        at com.google.firebase.auth.internal.zzx.<clinit>(Unknown Source:4)
        at com.google.firebase.auth.internal.zzx.initialize(Unknown Source:1)
        at com.google.firebase.auth.internal.zzt.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.flags.Flag" on path: DexPathList[[zip file "/data/app/air.com.myapp-58WxhooEU127GGiz1ABl_g==/base.apk"],nativeLibraryDirectories=[/data/app/air.com.myapp-58WxhooEU127GGiz1ABl_g==/lib/arm, /data/app/air.com.myapp-58WxhooEU127GGiz1ABl_g==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.firebase.auth.internal.zzx.<clinit>(Unknown Source:4) 
        at com.google.firebase.auth.internal.zzx.initialize(Unknown Source:1) 
        at com.google.firebase.auth.internal.zzt.run(Unknown Source:6) 
        at android.os.Handler.handleCallback(Handler.java:789) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
```

## Environment ##
* Android Version: 4.4,5,7,8

* AIR Version: 31

```actionscript
 private function onSignInResult(e:AuthEvents):void {
        if (e.result == Auth.RESULT_SUCCESS) {
            Auth.listener.removeEventListener(AuthEvents.SIGN_IN_RESULT, onSignInResult);
            if (FirebaseUser.isAvailable){
                FirebaseUser.getIdToken(false);
                FirebaseUser.listener.addEventListener(FirebaseUserEvents.GET_USER_TOKEN, onGetUserToken);
            }
   }
}
```

## Steps to Reproduce ##
 Call
`FirebaseUser.getIdToken(false);  `
and wait 60 minutes

## Known Workarounds ##
None

**Comment by myflashlab** [comment]
interesting one. Thanks for pointing that out ```com.google.android.gms.flags.Flag``` is available in [googlePlayServices_flags.ane](https://github.com/myflashlab/common-dependencies-ANE/blob/master/googlePlayServices/googlePlayServices_flags.ane) I'll be fixing the docs

**Comment by AlexUrrutia** [comment]
Added googlePlayServices_flags.ane it works now, thanks
