### ISSUE TITLE
(FCM) "click_action": "MY_INTENT" Bug

### ISSUE THREAD

**Issue by flashomer** [myflashlab/Firebase-ANE#37]
"click_action": "MY_INTENT" bug is android.
http://gupon.net/fcm/1.png

and android badge problem.
http://gupon.net/fcm/2.png

http://screencast-o-matic.com/watch/cD6UbojJUP

**Comment by myflashlab** [comment]
We would appreciate if you can send Screenshots in English. I'm not sure if I'm correct but [this screenshot](http://gupon.net/fcm/1.png) is showing an error message?

Anyway, if adding the ```MY_INTENT``` is crashing your app, it is very probable that you have missed to add the required activity/services to your app explained [here](https://github.com/myflashlab/Firebase-ANE/wiki/G.1-Add-FCM#add-the-fcm-ane-to-your-app)

```xml
<!-- Required by firebase_messaging.ane -->
                <service android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingService">
                    <intent-filter>
                        <action android:name="com.google.firebase.MESSAGING_EVENT"/>
                    </intent-filter>
                </service>
                <service android:name="com.myflashlab.firebase.fcm.MyFirebaseInstanceIDService">
                    <intent-filter>
                        <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
                    </intent-filter>
                </service>
                <activity 
                    android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingIntent" 
                    android:theme="@style/Theme.Transparent"
                    android:exported="false"
                    android:noHistory="true"
                    android:clearTaskOnLaunch="true"
                    android:hardwareAccelerated="false"
                    android:stateNotNeeded="true">
                    <intent-filter>
                        <action android:name="MY_INTENT" />
                        <category android:name="android.intent.category.DEFAULT" />
                    </intent-filter>
                </activity>
```

**NOTE:** do NOT change any package address in these services/activity. use them as they are.
**HINT:** only if you see a package starting with ```air......``` you should change it to your own app package name. leave everything else as they are.

Let me know how it goes. If you still have any problem, also send us the error logs so we can help you more.

**Comment by flashomer** [comment]
[this screenshot ](http://gupon.net/fcm/1.png) writers: 
"FCM stopped"
"Open the application again"

Application is running on, but the application gives off error.


I'm already attached to this my app.
```
<!-- Required by firebase_messaging.ane -->
                <service android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingService">
                    <intent-filter>
                        <action android:name="com.google.firebase.MESSAGING_EVENT"/>
                    </intent-filter>
                </service>
                <service android:name="com.myflashlab.firebase.fcm.MyFirebaseInstanceIDService">
                    <intent-filter>
                        <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
                    </intent-filter>
                </service>
                <activity
                    android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingIntent"
                    android:theme="@style/Theme.Transparent"
                    android:exported="false"
                    android:noHistory="true"
                    android:clearTaskOnLaunch="true"
                    android:hardwareAccelerated="false"
                    android:stateNotNeeded="true">
                    <intent-filter>
                        <action android:name="MY_INTENT" />
                        <category android:name="android.intent.category.DEFAULT" />
                    </intent-filter>
                </activity>

```

**Comment by myflashlab** [comment]
Ok, I can see that when you are adding the ```MY_INTENT``` line, the notification won't get opened anymore. Can you send us the error log by connecting your device to Android Studio? There must be some error messages there which should spot the problem.

P.S  Cool screen casting I should say by the way :) what software is it? it's duplicating your real device screen?

**Comment by flashomer** [comment]
how will I do the error log by connecting your device to Android Studio?

**Comment by myflashlab** [comment]
just install Android Studio and open the logcat window while your device is connected to your computer. the logs will be printed there. When the error happens, you will see it in the logs.

**Comment by flashomer** [comment]
http://imgur.com/J31JV47
http://imgur.com/GXyl5wg

```
10-31 16:56:19.239: W/Instrumentation(5363): Unresolved intent: cmp: null
10-31 16:56:19.239: W/Instrumentation(5363): Unresolved intent: data: air.com.fcmtest2://%7b%22google.sent_time%22%3a1477925775685%2c%22obj%22%3a%22%7b%5c%22variable2%5c%22%3a%5c%22value2%5c%22%2c%5c%22variable1%5c%22%3a%5c%22value1%5c%22%7d%22%2c%22collapse_key%22%3a%22air.com.fcmtest2%22%2c%22from%22%3a%221033512142342%22%2c%22google.message_id%22%3a%220%3a1477925775710246%258b9090618b909061%22%7d
10-31 16:56:19.239: D/AndroidRuntime(5363): Shutting down VM
10-31 16:56:19.239: W/dalvikvm(5363): threadid=1: thread exiting with uncaught exception (group=0x9ccfeb20)
10-31 16:56:19.249: I/Process(5363): Sending signal. PID: 5363 SIG: 9
10-31 16:56:19.249: D/AndroidRuntime(5363): procName from cmdline: air.com.fcmTest2
10-31 16:56:19.249: E/AndroidRuntime(5363): in writeCrashedAppName, pkgName :air.com.fcmTest2
10-31 16:56:19.249: D/AndroidRuntime(5363): file written successfully with content: air.com.fcmTest2 StringBuffer : ;air.com.fcmTest2
10-31 16:56:19.249: E/AndroidRuntime(5363): FATAL EXCEPTION: main
10-31 16:56:19.249: E/AndroidRuntime(5363): Process: air.com.fcmTest2, PID: 5363
10-31 16:56:19.249: E/AndroidRuntime(5363): java.lang.RuntimeException: Unable to start activity ComponentInfo{air.com.fcmTest2/com.myflashlab.firebase.fcm.MyFirebaseMessagingIntent}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=air.com.fcmTest2://{"google.sent_time":1477925775685,"obj":"{\"Variable2\":\"value2\",\"Variable1\":\"value1\"}","collapse_key":"air.com.fcmTest2","from":"1033512142342","google.message_id":"0:1477925775710246%8b9090618b909061"} flg=0x14000000 }
10-31 16:56:19.249: E/AndroidRuntime(5363): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
10-31 16:56:19.249: E/AndroidRuntime(5363): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
10-31 16:56:19.249: E/AndroidRuntime(5363): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
10-31 16:56:19.249: E/AndroidRuntime(5363): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
10-31 16:56:19.249: E/AndroidRuntime(5363): 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-31 16:56:19.249: E/AndroidRuntime(5363): 	at android.os.Looper.loop(Looper.java:136)
10-31 16:56:19.249: E/AndroidRuntime(5363): 	at android.app.ActivityThread.main(ActivityThread.java:5021)
10-31 16:56:19.249: E/AndroidRuntime(5363): 	at java.lang.reflect.Method.invokeNative(Native Method)
10-31 16:56:19.249: E/AndroidRuntime(5363): 	at java.lang.reflect.Method.invoke(Method.java:515)
10-31 16:56:19.249: E/AndroidRuntime(5363): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:827)
10-31 16:56:19.249: E/AndroidRuntime(5363): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:643)
10-31 16:56:19.249: E/AndroidRuntime(5363): 	at dalvik.system.NativeStart.main(Native Method)
10-31 16:56:19.249: E/AndroidRuntime(5363): Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=air.com.fcmTest2://{"google.sent_time":1477925775685,"obj":"{\"Variable2\":\"value2\",\"Variable1\":\"value1\"}","collapse_key":"air.com.fcmTest2","from":"1033512142342","google.message_id":"0:1477925775710246%8b9090618b909061"} flg=0x14000000 }
10-31 16:56:19.249: E/AndroidRuntime(5363): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1727)
10-31 16:56:19.249: E/AndroidRuntime(5363): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1511)
10-31 16:56:19.249: E/AndroidRuntime(5363): 	at android.app.Activity.startActivityForResult(Activity.java:3430)
10-31 16:56:19.249: E/AndroidRuntime(5363): 	at android.app.Activity.startActivityForResult(Activity.java:3391)
10-31 16:56:19.249: E/AndroidRuntime(5363): 	at android.app.Activity.startActivity(Activity.java:3633)
10-31 16:56:19.249: E/AndroidRuntime(5363): 	at android.app.Activity.startActivity(Activity.java:3601)
10-31 16:56:19.249: E/AndroidRuntime(5363): 	at com.myflashlab.firebase.fcm.MyFirebaseMessagingIntent.onCreate(MyFirebaseMessagingIntent.java:81)
10-31 16:56:19.249: E/AndroidRuntime(5363): 	at android.app.Activity.performCreate(Activity.java:5336)
10-31 16:56:19.249: E/AndroidRuntime(5363): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
10-31 16:56:19.249: E/AndroidRuntime(5363): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
10-31 16:56:19.249: E/AndroidRuntime(5363): 	... 11 more

```

**Comment by myflashlab** [comment]
Are you receiving this problem on all devices you are testing on? If it's happening only on a specific device, would you send us the Model and Android version?

**Comment by flashomer** [comment]
bluestacks emulator and general mobile gm 5 plus
I think all the androids have the same error.

**Comment by myflashlab** [comment]
We will investigate this and update this ticket a.s.a.p

**Comment by FabioNani** [comment]
Waiting for resolution!

**My problem is identical!**

**Comment by mikron123** [comment]
Same here! I wasted so many hours on this bug.. it's impossible to open the app and handle the notification data.....

**Comment by myflashlab** [comment]
Guys, we're not able to duplicate this problem. And although MANY other devs are using the FCM ANE, they don't seem to be facing this problem. You need to somehow provide us with more info. Anything that would help us see the problem. If we can't see the bug, we can't kill it!

A wild guess would be if you have activated multidexing in your manifest? ```android:name="android.support.multidex.MultiDexApplication"```? Check sample manifest files we have on Github for more information about where you should add this.

**Comment by mikron123** [comment]
we should add this or we should not?? Unclear from the reply.
Plus, since multiple devs are having this bug, why don't you just put a link here with your sample project
which works, and we will understand by slowly upgrading it to ours.
My project is VERY basic, and still has this bug. Did you try to add all of your firebase ANEs when testing?

**Comment by myflashlab** [comment]
yes, you should add it. the sample projects are for [intelliJ](https://github.com/myflashlab/Firebase-ANE/tree/master/AIR), [FlashDevelop](https://github.com/myflashlab/Firebase-ANE/tree/master/FD) and [AdobeAnimate](https://github.com/myflashlab/Firebase-ANE/tree/master/FLA)

This is also shown in wiki setup https://github.com/myflashlab/Firebase-ANE/wiki/A.4.-Initialize-Firebase-in-your-app

@mikron123 Since you have a basic project, can you send us a demo apk? Something which we can run here on our devices and then send FCM messages to it to be able to see the problem?

**Comment by mikron123** [comment]
Is it really difficult for you guys to upload a working base project so I can understand in 10 minutes what's the difference?

**Comment by mikron123** [comment]
Solved it: I was listening to FCM.listener instead of NativeApplication.nativeApplication with InvokeEvent.INVOKE. 
It was confusing, I would advise you to merge the "send 1st push" into a single document of how to send and receive a push from end to end.

Thanks.

**Comment by myflashlab** [comment]
glad to hear that. have you checked this page https://github.com/myflashlab/Firebase-ANE/wiki/G.3-First-Message#receive-payload-data-when-opening-the-app-from-notification

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
