### ISSUE TITLE
App launch error when installed new

### ISSUE THREAD

**Issue by AlexUrrutia** [myflashlab/Firebase-ANE#62]
**App crashes on first launch after install from Google Play Store**

`java.lang.RuntimeException: Unable to instantiate receiver com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver" on path: DexPathList[[zip file "/data/app/air.com.mysite.app-1/base.apk"],nativeLibraryDirectories=[/data/app/air.com.mysite.app-1/lib/arm, /vendor/lib, /system/lib]]
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2620)
	at android.app.ActivityThread.access$1700(ActivityThread.java:155)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1394)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5343)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver" on path: DexPathList[[zip file "/data/app/air.com.mysite.app-1/base.apk"],nativeLibraryDirectories=[/data/app/air.com.mysite.app-1/lib/arm, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2615)
	... 9 more
	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 11 more
Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
`

**Comment by AlexUrrutia** [comment]
Solved, was missing a dependency...

**Comment by AGulev** [comment]
Hi @AlexUrrutia Do you remember which exactly dependency?
